#!/bin/bash
codedir="../code/"
python3 ${codedir}S11_at_frequency_tand_sweep.py
python3 ${codedir}S11_at_frequency_UCSweep.py
python3 ${codedir}frequency_shifts_epsr.py
python3 ${codedir}frequency_shifts.py
for eps in 4.5 4.1; 
    do python3 ${codedir}frequency_shifts_tand.py --eps $eps;
done;
python3 ${codedir}S11_at_frequency_lz_sweep.py
python3 ${codedir}frequency_shifts_lz.py
python3 ${codedir}S11_at_frequency_UCSweep.py
python3 ${codedir}perfect_epsilon.py
